#!/usr/bin/env bash
# 4. Not found page 404
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
echo -e "Ceci n'est pas une page" | sudo tee /var/www/html/la_404.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\terror_page 404 \/la_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
