#!/usr/bin/env bash
# 1. Install your load balancer
sudo apt-get update
sudo apt-get -y install haproxy
echo "listen 4426-lb-01
        bind 0:80
        mode http
        stats enable
        balance roundrobin
        option httpclose
        option forwardfor
        server 4426-web-01 54.224.105.134 check port 80
        server 4426-web-02 34.239.247.122 check port 80
        " | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
