#!/bin/bash
shellcheck 1-for_best_school
shellcheck 2-while_best_school
shellcheck 3-until_best_school
shellcheck 4-if_9_say_hi
shellcheck 5-4_bad_luck_8_is_your_chance
shellcheck 6-superstitious_numbers
shellcheck 7-clock
shellcheck 8-for_ls
shellcheck 9-to_file_or_not_to_file
shellcheck 10-fizzbuzz
